### ISSUE TITLE
All user defined PLATFORM.performance marks and measures are cleared after store.dispatch

### ISSUE THREAD

**Issue by vitar** [aurelia/store#111]
**I'm submitting a bug report**

* **Library Version:**
1.6.0

**Please tell us about your environment:**
* **Operating System:**
Windows 10

* **Node Version:**
10.15.3

* **NPM Version:**
6.4.1

* **JSPM OR Webpack AND Version**
JSPM 0.16.55

* **Browser:**
Chrome 88

* **Language:**
TypeScript

**Current behavior:**
`PLATFORM.performance` app/user defined marks and measures are cleared after requesting `store.dispatch`.

**Expected/desired behavior:**

* **What is the expected behavior?**
`PLATFORM.performance` app/user defined marks and measures should not be cleared after requesting `store.dispatch`.

* **What is the motivation / use case for changing the behavior?**
We use `PLATFORM.performance` to measure application/API performance. When application is using aurelia-store, its dispatch method may clear all marks/measures and reporting is broken.
Looking at aurelia-store code, looks like it clears all marks/measures regardless of key owner, while it should clear aurelia-store key owned marks/measures only.

**Comment by zewa666** [comment]
Ouch thanks for catching that. Would you provide a PR to fix that?

**Comment by vitar** [comment]
Let me see what I can do.

**Comment by vitar** [comment]
Around next week I'll be able to contribute.

**Comment by vitar** [comment]
Hey, I got error pushing fix branch: `ERROR: Permission to aurelia/store.git denied to vitar.`
Please guide me through to get this done.

**Comment by zewa666** [comment]
OK ouch. Yeah just fork the repo and create the PR from there onto this upstream

**Comment by vitar** [comment]
PR is created https://github.com/aurelia/store/pull/112
Can't link to the issue.
Unit tests has passed, but some reporting has failed, please take a look.

**Comment by vitar** [comment]
What is the process of publishing a fixed version to NPM? When could I expect it?

**Comment by zewa666** [comment]
I've just pinged @EisenbergEffect for this as he takes care about the v1 releases wheras V2 already happens through a larger crowd.

**Comment by zewa666** [comment]
@vitar 1.7.0 fresh out of the bakery. Thanks again for your contribution
