### ISSUE TITLE
tslib and rxjs's tslib versions mismatch

### ISSUE THREAD

**Issue by Isoldhe** [aurelia/store#134]
**I'm submitting a bug report**

* **Library Version:**
1.7.2

**Please tell us about your environment:**
* **Operating System:**
Windows 10

* **Node Version:**
V18.12.1

* **NPM Version:**
8.11.0

* **JSPM OR Webpack AND Version**
Aurelia-cli V3.0.1

* **Browser:**
Chrome 107.0.5304.106

* **Language:**
TypeScript 4.6.4

**Current behavior:**
When using the basic Store example from the [docs](https://aurelia.io/docs/plugins/store#subscribing-to-the-stream-of-states) in a typescript project, compiling fails with the following error:
```
Compiled with problems:

WARNING

tslib
  Multiple versions of tslib found:
    1.14.1 ./~/rxjs/~/tslib
    2.4.1 ./~/tslib

Check how you can resolve duplicate packages: 
https://github.com/darrenscerri/duplicate-package-checker-webpack-plugin#resolving-duplicate-packages-in-your-bundle
```
I made a working example: https://github.com/Isoldhe/Aurelia-TestStore

When creating the project, these were the options I chose, if that matters:
```
√ Please name this new project: » TestStore
√ Would you like to use the default setup or customize your choices? » Custom Project
√ App or Plugin? » App
√ Which bundler would you like to use? » Webpack
√ What platform are you targeting? » Web
√ What transpiler would you like to use? » TypeScript
√ How would you like to setup your HTML template? » None
√ What css preprocessor would you like to use? » Sass
√ Do you want to add PostCSS processing » None
√ Which unit test runner would you like to use? » Jest
√ Would you like to configure e2e integration testing? » None
√ What is your default code editor? » Visual Studio Code
√ Which features do you want to scaffold into your project? » Navigation App
√ Would you like to add a Dockerfile? » No
[makes] Project TestStore has been created.
√ Do you want to install npm dependencies now? » Yes, use npm
```

**Expected/desired behavior:**
the rxjs library installed by Aurelia Store should be updated to the latest tslib as to avoid version collision.

Thank you!

**Comment by zewa666** [comment]
hey @Isoldhe, thanks for the report.
we're at it and should have the new store version 2.0.0 (a breaking change) released/published soon.

**Comment by zewa666** [comment]
its published on npm
