### ISSUE TITLE
Typings are missing in 2.0.0

### ISSUE THREAD

**Issue by vilnytskyi** [aurelia/store#143]
**I'm submitting a bug report**

* **Library Version:**
2.0.0

**Please tell us about your environment:**
* **Operating System:**
Windows 11

* **Browser:**
all

* **Language:**
TypeScript

**Current behavior:**
`aurelia-store.d.ts` is referenced in `package.json` but not present in dist folder of [latest npm package](https://www.npmjs.com/package/aurelia-store/v/2.0.0?activeTab=explore)

**Expected/desired behavior:**
Typings should be present in order to be able to upgrade to latest version when using TypeScript.

**Comment by zewa666** [comment]
ouch, must be an issue with the build tools update. I'll get to it asap as I can

**Comment by bigopon** [comment]
Typings has been released in 2.0.1
Thanks @vilnytskyi
