### ISSUE TITLE
Cannot use the store in a config pipeline step

### ISSUE THREAD

**Issue by viqashussain** [aurelia/store#35]
**I'm submitting a bug report**

* **Library Version:**
major

**Please tell us about your environment:**
* **Operating System:**
Windows 10

* **Node Version:**
v8.11.2

* **NPM Version:**
5.6.0

* **JSPM OR Webpack AND Version**
webpack v4.11.0

* **Browser:**
all

* **Language:**
all

**Current behavior:**
Cannot use the store using the @connectTo decorator or manually subscribing in a config pipeline step, as the bind lifecycle function does not exist. state is always undefined. 

**Expected/desired behavior:**
For the state to be populated in the config pipeline steps.

* **What is the expected behavior?**
For the state to be populated in the config pipeline steps.

* **What is the motivation / use case for changing the behavior?**
If the state is not populated, you'll need to manually inject the Store in, and manually get the data from the state, which isn't nice.

I've also raised a question on StackOverFlow which you can find [here](https://stackoverflow.com/questions/50605038/state-is-always-undefined-when-using-the-connectto-decorator-in-a-config-pipeli).

**Comment by zewa666** [comment]
That is correct, the connectto decorator is primarily meant for components having lifecycle-hooks. You could provide the `setup` parameter to connectto and set it to `run` as its going to call your original implementation afterwards but there wouldnt be an appropriate teardown method. So manually injecting the Store and subscribing to the state as shown in the docs is the way to go here.
