### ISSUE TITLE
Thoughts on multiple selectors in connectTo decorator with propertyChanged calls

### ISSUE THREAD

**Issue by jmzagorski** [aurelia/store#36]
**I'm submitting a feature request**

* **Library Version:**
0.24.2

**Please tell us about your environment:**
* **Operating System:**
Windows 10

* **Browser:**
all
* **Language:**
Typescript

**Current behavior:**
The decorator calls one selector that populates the `state` or supplied `settings.target` in the view model and one `onChanged` is allowed

**Expected/desired behavior:**
Thank you for taking the time to create this plugin. I have been using Aurelia + Redux for over a year now so I am glad to see this. I am looking at removing Redux and using this library for our large Aurelia App. 

* **What is the expected behavior?**
Please forgive me in advanced since I opened this request from the viewpoint of using redux tools and patterns so RxJs may solve what I am about to request in another way. Do you plan on supporting multiple selectors from the decorator if the view model needs different slices from the state? For example:

```typescript
const state = {
  selector: {
    frameworks: (store) => store.state.pluck("frameworks"),
    databases: (store) => store.state.pluck("databases")
  }
}

@connectTo<State>(state)
export class App {
   ...
}
```

(where `frameworks` and `databases` are the target properties on the view model rather than supplying a `settings.target`.). 

You could take it one step farther and act like the `@observable` decorator and call `frameworksChanged(newValue, oldValue)` and `databasesChanged(newValue, oldValue)` rather than the user passing a separate function for `onChanged` in case they just care about the change to one of their state slices

* **What is the motivation / use case for changing the behavior?**
Gives another way to use the decorator

**Comment by zewa666** [comment]
Very nice idea. Im on vacation right now but will add this once back

**Comment by jmzagorski** [comment]
Great and enjoy your vacation! I will put the code below I use for redux in case it helps. I would do a PR, but I am not sure how you want to handle subscribing to multiple sources. Right now you grab the one source in the `getSource` function and subscribe in the setup function, but multiple selectors would return multiple sources to subscribe to so the `getSource` function may not be a good candidate.

```javascript
// i put the getType logic after this snippet so you can see it for reference
// since typeof [] and typeof null return 'Object' as well
if (settings && getType(settings.selector) === 'Object') {
  Object.entries(settings.selector).map(s => {
    const oldValue = this[s[0]];
    let newValue = null;

   try {
      newValue = s[1](state);
    } catch (e) {
      e.message = `${s[0]}: ${s[1]} selector failed: ` + e.message;
      throw e;
    }

    const changeHandler = `${s[0]}Changed`;
    this[s[0]] = newValue;

    // like the @observable decorator
    if (changeHandler in this) {
      this[changeHandler](newValue, oldValue);
    } else if ('propertyChanged' in this) {
      this.propertyChanged(s[0], newValue, oldValue);
    }
  });
}
```

```javascript
// i was using this function to make sure an object literal was being used 
// since typeof [], type of null return 'object'
  export const getType = obj => {
  const type = typeof obj;

  if (type !== 'object') return type; // primitive or function
  if (obj === null) return 'null';    // null

  // Everything else, check for a constructor
  const ctor = obj.constructor;
  const name = typeof ctor === 'function' && ctor.name;

  return typeof name === 'string' && name.length > 0 ? name : 'object';
};
```

**Comment by zewa666** [comment]
So in order not to make a breaking change and yet provide maybe an additional feature what about the following:

1. We'll add a `_partialSubscriptions` of type `Subscription[]`
2. If the settings.selector is an object with keys, themselves returning functions these individual subscriptions can be added to `_partialSubscriptions` and handled for subscription and unsubscription
3. Leverage the old `_stateSubscription` private in this case to `merge` all partial observables and create a full subscription.

How does this sound? That would also keep the `setup` and `teardown` in place for the fatty subscription and your proposed autoChanged detection as a good alternative for the detailed configuration.

I think you covered there most of the implementation by yourself and with regards to where the source detection belongs, `getSource` is called exactly once internally, as such changing the signature to return `Observable<any>[]` shouldn't be too much of a hassle. `decorator.spec.ts` would be the accompanying test spec file.

Given that would you like to give it a go and do the initial implementation by yourself? Just follow the usual [contribution guidelines](https://github.com/aurelia/store/blob/master/CONTRIBUTING.md)

**Comment by jmzagorski** [comment]
Thanks, I can give this a go. I will probably be able to start this next week.

**Comment by zewa666** [comment]
as said don't be shy throwing things around internally. We just want to make sure to keep existing features working :)

**Comment by jmzagorski** [comment]
I thought i could get some contributing done while on "vacation" this week (not a real vacation just time away from my real job), but i was not able to do much. I am back at my desk next week so I will be able to start it then.
