### ISSUE TITLE
installation problem with rxjs

### ISSUE THREAD

**Issue by alexisargyris** [aurelia/store#37]
**I'm submitting a bug report**

* **Library Version:**
0.24.2

**Please tell us about your environment:**
* **Operating System:**
Windows [10]

* **Node Version:**
6.9.2

* **NPM Version:**
3.10.6

* **JSPM OR Webpack AND Version**
JSPM 0.16.34

* **Browser:**
Chrome 67

* **Language:**
TypeScript 2.9.1

**Current behavior:**
Following the installation directions:

````
npm install aurelia-store --save
````

and in aurelia.json:

````
{
	"name": "aurelia-store",
	"path": "../node_modules/aurelia-store/dist/amd",
	"main": "aurelia-store"
},
{
	"name": "rxjs",
	"path": "../node_modules/rxjs",
	"main": false
}
````

I run my app locally using:

````
au run --env dev --watch
````

and I get

````
 ------- File not found or not accessible ------
| Location: C:/.../node_modules/rxjs.js
| Requested by: C:/.../src/app.js
| Is this a package? Make sure that it is configured in aurelia.json and that it is not a Node.js package
 -----------------------------------------------
 ------- File not found or not accessible ------
| Location: C:/.../node_modules/rxjs/operators.js
| Requested by: C:/.../src/app.js
| Is this a package? Make sure that it is configured in aurelia.json and that it is not a Node.js package
 -----------------------------------------------
````

**Expected/desired behavior:**

* **What is the motivation / use case for changing the behavior?**
Please note that aurelia-store was working great until yesterday when I had to remove it temporarily and then tried to re-install it.

**Comment by alexisargyris** [comment]
Just noticed the warning provided [here](https://aurelia.io/docs/plugins/store#granular-patched-rxjs-imports). I doubt it could be made any bolder, still I managed to overlook it...

**Comment by zewa666** [comment]
Yeah its a bit disappointing to how rxjs handles the Version bump but all in all understandable due to massive breaking changes. Sry you wasted time but at least this issue will help others to stumble upon your findings.

**Comment by alexisargyris** [comment]
Please consider updating the documentation in aurelia.io so that newcomers to aurelia-store (a really great plugin!) do not get into trouble.

For example:

* Section "Getting Started" seems now to be pertinent only to users of RxJS <= v.5.
* Section "Granular (patched) RxJS imports" is of key interest to new users. Maybe rename it?
* The aurelia-cli route (i.e. `au import aurelia-store`) didn't work for me, but I may have an older version of the cli.
* The rxjs-compat alternative ends up doing `npm install rxjs`. Is the entry to vendor bundle any different?
* Finally, the advice on how to avoid triggering a full RxJS bundle may confuse people still trying to install aurelia-store as they don't need to start out by playing around with Observables since they have aurelia-store for that!

**Comment by zewa666** [comment]
There seems to be a mix of requests there so how about you start with a PR outlining how you would see the optimal way and we can collaborate on that. The docs are part of this repo and get built from the .md files.

**Comment by alexisargyris** [comment]
Next week I'll try to get aurelia-store working again with RxJS v6. If, in the process, I end up with any specific ideas on how to present the process in a more clear way I'll get back to you. Thanks a lot.

**Comment by alexisargyris** [comment]
As it turns out @RomkeVdMeulen beat me to it and proposed most of the changes I had in mind. 
A detail that you may want to consider is to add in the dependencies section of aurelia.json the configuration of rxjs/operators.

**Comment by zewa666** [comment]
Good idea, lets track that over here https://github.com/aurelia/store/issues/43
