### ISSUE TITLE
State gets saved as string instead of object

### ISSUE THREAD

**Issue by dannyBies** [aurelia/store#51]
I'm submitting a bug report

Library Version:
0.24.2

Browser:
Chrome 67

Current behavior:
Moment.JS objects are saved as a string in the Redux DevTools

Expected/desired behavior:
Moment.JS object is saved as it is instead of a string.
Related to https://github.com/reduxjs/redux-devtools/issues/340

What is the motivation / use case for changing the behavior?
I have a state that is something like:
```
export interface IState {
    test: moment.Moment;
}
```

If I use the Chrome Redux DevTools I see my test property but instead of a moment object it is.
`test(pin): "2018-07-30T00:00:00.000Z"`

This makes it impossible to go forward/backwards in the state because my bindings expect a moment object in the state but it's a string which makes the application crash because certain functions are not available.

It seems that we can set serialize: true on the redux devtools extension could we add this to the aurelia-store?

**Comment by zewa666** [comment]
Thats actually understandable since all die sent to the redux devtools Extension needs to be serialized first. I guess there is a toString overload for your Moment object which turns it into a string when passed to JSON.stringify. So its not really related to Aurelia Store per se. What you could try though is to convert the string back into an object via a Middleware.

**Comment by zewa666** [comment]
Did you have any success with the above mentioned workflow @dannyBies ?

**Comment by dannyBies** [comment]
Thanks for your reply!

Sorry, I've been on a short holiday, I'm back now.

In my state I have a combination of string dates and moment dates
``  date: string ``
`` date2: moment.Moment `` 

How would I know which objects to convert in the middleware?

I've been tinkering with the store implementation and if I use
`` this.devTools = PLATFORM.global.__REDUX_DEVTOOLS_EXTENSION__.connect({ serialize: false }); `` 
In the store.js my problem is solved and I can use the DevTools to jump through state.

My idea was to create a pull request and add a store option to add this functionality to choose if you want to serialize or not (https://github.com/zalmoxisus/redux-devtools-extension/blob/master/docs/API/Arguments.md#serialize)

**Comment by zewa666** [comment]
I think that's a great idea. What you'll want to do is to update the [StoreOptions](https://github.com/aurelia/store/blob/master/src/store.ts#L21) interface, maybe already with an complex object `devTools: { serialize: BOOLEAN }` so that we can extend this with any other options in future.
