### ISSUE TITLE
Support TS 3.0 tuples in rest parameters and spread expressions

### ISSUE THREAD

**Issue by zewa666** [aurelia/store#53]
So far one annoyance with the stores `dispatch` function was that actions which require params where not type safe.

What does that mean ... e.g

```typescript
const addAction = (state: State, valueA: number, valueB: number) {
  state.total = valueA + valueB;
} 

// current
1. store.dispatch(addAction);
2. store.dispatch(addAction, "A", "B");
3. store.dispatch(addAction, 1);
```

with TS < 3 we wouldn't see any issues from above calls, because the spread parameters provided to the called Reducer<T> wouldn't be typesafe.

With TS 3 we can have type-safe tuples. So the result would be

```typescript
// with TS 3
1. Expected 3 arguments, but got 1.
2. Argument of type '"1"' is not assignable to parameter of type 'number'.
3. Expected 3 arguments, but got 2.
```

This would require a type change of Reducer and the dispatch function.

```typescript
export type Reducer<T> = (state: T, ...params: any[]) => T | false | Promise<T | false>;
// becomes
export type Reducer<T, P extends any[] = any[]> = (state: T, ...params: P) => T | false | Promise<T | false>;

public dispatch(reducer: Reducer<T> | string, ...params: any[]) {
// becomes
public dispatch<P extends any[]>(reducer: Reducer<T, P> | string, ...params: P) {

Reducer<T>
// becomes
Reducer<T, P>
```

Images might say more than thousand words:

![dispatch-intellisense](https://user-images.githubusercontent.com/2861414/43593045-30e05060-9677-11e8-900b-d40d35739bc6.png)

![dispatch-intellisense2](https://user-images.githubusercontent.com/2861414/43593143-614e202e-9677-11e8-9e48-6a4bc0e89e3f.png)

---

The downside of implementing this is that we'd require a higher version of TypeScript, which would introduce a potential breaking change

**Comment by jmezach** [comment]
Personally I think the benefits far outweigh the risks involved here, but I might not be the best judge ;). That being said, this does bring me to another interesting point. Currently the design requires the action to be registered using registerAction, with a string parameter. At dispatch time this string is not needed and you can just pass in the reducer directly, which will probably be the way to go for the above to work.

So why do we need to pass in a string when registering the action? What purpose does it have, especially with this change?

**Comment by zewa666** [comment]
@jmezach I tend to agree, I still want to figure out what would be the minimal obtrusive way for consumers. So if there could be at least a descriptive error message, telling you what happened, this would already be better as just a hard break and your IDE screaming all over the place about syntax it doesn't understand :)

With regards to registerAction and strings. Those are primarily used for error handling, the logging feature and the devTools, so that steps get named nicely. No we can't auto infer the name as the default as certain bundlers like Webpack screw up `myFunction.name` during compilation.

**Comment by zewa666** [comment]
Not really without having to keep two long-running versions alive. I guess this will have to wait a few more days and we'll than go to official v1.0.0

**Comment by zewa666** [comment]
as requested by @gimerstedt great idea we can now use the same thing for the dispatchify function:

![dispatchify-typesafe](https://user-images.githubusercontent.com/2861414/43732297-8dab20b2-99b1-11e8-8c38-30141f1f4e4c.jpg)

**Comment by zewa666** [comment]
V 1.0.0 released 🎉
