### ISSUE TITLE
Documentation for input binding/validation

### ISSUE THREAD

**Issue by jordanmaslyn** [aurelia/store#54]
Hi there, forgive me if this is the wrong mode for requesting this, but here goes:

My team is in the process of implementing Aurelia Store throughout several of our apps, however we are having troubles with "best practices" in terms of inputs and validation.

It seems like the best practice for a text input would `value.to-view="state.textValue"` and then `change.delegate="updateTextValue($event)"`, where `updateTextValue` dispatches the requisite action.

Where we are having issues though is that some of our inputs are nested within an array. For example, we have an array of `clients` and we loop through those with `repeat.for="client of state.clients"` and then have a field to change a given property of each client (e.g. `value.to-view="client.email"`) .

However, when the state observable refreshes, the repeat.for updates and wipes out any error messages/classes created from the ValidationRenderer results.

I wanted to create a reproduction but it appears the gistrun doesn't offer aurelia-store yet. Any thoughts? Is there a better way to accomplish this?

**Comment by zewa666** [comment]
I'm sorry about the missing gist.run here is an updated one https://gist.run/?id=6e5d8a599932dcdd04f4363c7c731a1a

**Comment by jordanmaslyn** [comment]
@zewa666 Thanks for adding that! Seems aurelia-validation is still missing from that bundle. Are you able to easily add that in since the issue I am experience is dependent on the interaction between store/validation.

**Comment by zewa666** [comment]
@jordanmaslyn updated the gist with Aurelia Validation + Aurelia I18N

**Comment by zewa666** [comment]
Tbh I have no expertise with the validation plugin, maybe @fkleuver or @bigopon can help out here?

**Comment by fkleuver** [comment]
@jordanmaslyn @zewa666  It is indeed this error: https://github.com/aurelia/validation/issues/350#issuecomment-392299077
You're having both version 1.x and 2.x of binding in your bundle. Try upgrading all your aurelia deps, this problem is solved in the latest versions.

**Comment by jordanmaslyn** [comment]
@zewa666 Is that something you are able to fix from your bundle?

**Comment by fkleuver** [comment]
@zewa666 I can see in your package-lock that there's a few `aurelia-binding` 1.x's hiding in there. Probably best to just update everything to latest tbh

**Comment by zewa666** [comment]
I've updated the master with cleaned up dependencies.

@jordanmaslyn can you try to do the following:
* Install aurelia-store from github/master
* delete your package-lock.json
* delete your node_modules folder
* npm install
