### ISSUE TITLE
connectTo does not work in IE11

### ISSUE THREAD

**Issue by jordanmaslyn** [aurelia/store#59]
**I'm submitting a bug report**

* **Browser:**
IE 11

* **Language:**
all

**Current behavior:**
Use of connectTo breaks in IE11 with the error `ERROR [app-router] TypeError: Object expected`. This prevents the app from running at all.

**Expected/desired behavior:**
I created a GistRun to repro the issue at https://gist.run/?id=d7171f9290bb9d777399b0b65ab345b9 but it turns out GistRun does not work in IE11 either

* **What is the expected behavior?**
I expect to be able to load my app as normal.

* **What is the motivation / use case for changing the behavior?**
For Aurelia based apps using connectTo to work in IE11.

**Comment by zewa666** [comment]
Have you used the object.entries polyfill in addition to aurelia-polyfills?

**Comment by jordanmaslyn** [comment]
Yes, we have been using the MDN polyfill from https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/entries#Polyfill. Any other thoughts on what the cause may be? 

If it helps, another part of the error reads `SCRIPT5007: Unable to set property '@@name' of undefined or null reference
aurelia-polyfills.js (48,1)`

**Comment by zewa666** [comment]
I'll try it out tomorrow on an Win7 VM with IE11. I've no idea out of my head what it could be instead.

**Comment by jordanmaslyn** [comment]
I have sidestepped the issue by turning off Aurelia polyfills (using the Aurelia Webpack plugin) and replacing it with babel-polyfill. Seems to be working fine at first runthrough. Obviously though it would be ideal for it to work out of the box to fulfill Aurelia's browser compatibility. If I can help diagnose in any way, please let me know. My machine where I was seeing the issue is Win10/IE11.

**Comment by zewa666** [comment]
@jordanmaslyn I cannot replicate the original issue. Can you maybe create a github repo for me to try out?

**Comment by zewa666** [comment]
@jordanmaslyn ping?

**Comment by jmzagorski** [comment]
@zewa666 would it help if it could attempt to use `Object.keys` instead? I was not aware of the IE limitation, and I think on windows 10 IE11 `Object.keys` is recognized.

**Comment by zewa666** [comment]
I guess so. At least the additional polyfill wouldnt be required.
