### ISSUE TITLE
Question: New State Value Not Acquired After Action Dispatched

### ISSUE THREAD

**Issue by yauri-io** [aurelia/store#60]
Using the latest version Aurelia-Store 1.0.0

initial-state.js
```javascript

export default {
    cart: []
}

```

main-state.js
```javascript
import {Store} from 'aurelia-store';

export class MainState {

  static inject = [Store];

  constructor(store) {
    this.store = store;
    this.stateSubscription = this.store.state.subscribe((state) => {
      this.instance = state;
    });
  }

}

```

cart-service.js
```javascript

import {MainState} from './main-state';
import {TaskQueue} from 'aurelia-framework';

export class CartService {

    static inject = [MainState, TaskQueue];

    constructor(mainState, taskQueue) {
        this.mainState = mainState;
        this.taskQueue = taskQueue;
    }

    pullCartFromServer() {
         const cart = await http.get('https://myserver.com/cart/cartId'); // returns an array
         setCart(cart); // action , assume it is working correctly, set cart of the initial state, synchronous code
         
         console.log(this.mainState.instance.cart.length) // I expect the length > 0, but it is always 0
         
        // if I do this, then the cart length is correct
       this.taskQueue.queueMicroTask(() => {
             console.log(this.mainState.instance.cart.length); 
       });
    }
}

```

From the sample code above, I'm wondering why my state not updated directly after the action dispatched? Is it expected behavior?

**Comment by zewa666** [comment]
Yes it is because the state cycle is async and the subscription as well. You can try to await the dispatch call inside your setCart method which should queue your call after it. In case you use an Aurelia binding though you would still need a queued microtask.

**Comment by yauri-io** [comment]
Thanks for the explanation.
But I still don't quite understand with "You can await the dispatch call inside your setCart method which should queue your call after it. That way using async/await it reads more sync codewise"
Is it in the documentation?

**Comment by yauri-io** [comment]
Ok, I found some articles explaining about the async state.
I'll read those.
Thanks again!

**Comment by yauri-io** [comment]
Ok, then I found about what to do in the [Aurelia Store documentation](https://aurelia.io/docs/plugins/store#dispatching-actions)

> Now keep in mind that an action might be async (really any middleware might be - you'll learn more about middleware later), and as such if you depend on the state being updated right after dispatching an action, make sure to await the call to dispatch.

And this is my dispatcher code update
```javascript
const setCartItems = async(items = []) => {
  await store.dispatch(CartActions.setCartItems, items);
};
```

Everything works as expected now 🍻

**Comment by zewa666** [comment]
This is what meant yes. The performance depends really on what happens in your action and/or middlewares. But it sounds neglectable in the case you've shown.

Im sorry you had to search so long for your answer, is there anything that could be changed in the Docs  to clarify this even more?

**Comment by yauri-io** [comment]
No problem with the search, it helps me to read in more detail.

Maybe adding a short example above the async action description will be helpful for people who never use state management API.
Overall, it's good! People only need to read carefully.

The example project you provided actually show my use case
https://github.com/zewa666/aurelia-store-examples/blob/ed30abbe91ce953d87df24ec9d0216f1dd65f238/services/src/developer/data/developer-actions.ts#L22

https://github.com/zewa666/aurelia-store-examples/blob/ed30abbe91ce953d87df24ec9d0216f1dd65f238/services/src/developer/add-developer-form.ts#L36

**Comment by zewa666** [comment]
OK great. Closing this as it seems fixed.
