### ISSUE TITLE
How to pluck a nested property within a repeat for over components

### ISSUE THREAD

**Issue by timbo333** [aurelia/store#63]
**I'm submitting a feature request**

* **Library Version:**
1.1.0

**Please tell us about your environment:**
* **Operating System:**
Windows [10]

* **Node Version:**
9.0.0

* **NPM Version:**
6.4.1

* **JSPM OR Webpack AND Version**
webpack 3.10.0

* **Browser:**
Chrome 69

* **Language:**
TypeScript 3.0.1

* **What is the expected behavior?**
Hi!

Currently I'm working on an implementation of the aurelia store using state slices.
During the development I ran into a problem which I would like to get your opinion on.

Context:
I got a state, which has some properties. These properties are lists, which contain new lists.
Somewhere in a nested list, I added a state slice.

example structure:
```
State {
	products: products[],
}

Product {
	id: number,
	editions: edition[],
}

Edition {
	id: number,
	name: string,
}
```

When I try to get the slice using the connectTo decorater, I have the problem that I need to know the index of the product and edition.
example: store.state.pipe(pluck("products", "IndexOfProducts", "editions", "IndexOfEditions", "name"))

Within the frontend files, I have different components to show each object.
I am repeating of the Products, and then over the Editions.
Meaning within an Edition component, I do not know which product I am.

Now I need to find a way to get the index of the product that I currently am looping through.
The current solutions I found are:
`this.store.state.pipe(pluck("products", overrideContext.parentOverrideContext.$index.toString(), "editions", overrideContext.$index.toString(), "name")).subscribe((state);`
Using the bindingContext to find out which index the parent object has, so I can determine which one I should get from the list.

The other one is:
```
store.state.pipe(map((state: IState) => state.products.find((prod) => prod.id === [SavedIdOfDesiredProduct])))
				.pipe(map((prod) => prod.editions.find((edition) => edition.id === [SavedIdOfDesiredEdition])))
				.pipe(pluck("name"))
```
				
The third solution is:
Using bindings on my components, to bind the correct object to the components.
I do not prefer to use the solution, because this has a big performance impact in my application.
				
				
Now all of these solution do not seem like the right option.
So I was wondering how you would try to tackle this problem.

**Comment by timbo333** [comment]
Heya,

sorry about my late reply.
I made a working example, without bindings.
But my problem is visible in the edition-overview.ts in the @connectTo decorator pattern.
Where I put two zero's to indicate which product and which editions I should show.
I would like to make those two indexes variable.

https://aurelia-typescript-zqbi2j.stackblitz.io

**Comment by timbo333** [comment]
https://stackblitz.com/edit/aurelia-typescript-zqbi2j
This is the edit link..

**Comment by zewa666** [comment]
Awesome. Im on vacation this week but will definitely take a look next week back at my PC

**Comment by zewa666** [comment]
So after looking at your example, I'm not sure how you obtain the `overrideContext`. Guess this was directly within the bind hook right?

I'd personally say looking at the example that this would be the way to go. The decorator can't ever have information about runtime behavior like the repeated index, because it operates on the static inspection of the class. That's when you should handle subscriptions by yourself, like what you did in your option a, by looking at `this.store...`.

As an alternative to access the overrideContext and calculate the parents and the editions iterator, you could instead bind the position as attribute for your editions element. So like

```html
<edition-overview pid.bind="$parent.$index" eid.bind="$index"></edition-overview>
```

Personally, without knowing what causes your perf hit, I'd prefer Option 3, where I'd pass in the `edition` entity directly to the element and let it handle what it needs.

**Comment by zewa666** [comment]
Again a very cool idea, haven't thought initially about that and for your use-case I think this is definitely the way to go. For everybody else reading, the context can also be passed as described in the [comment before](https://github.com/aurelia/store/issues/63#issuecomment-425652094).
