### ISSUE TITLE
Running in nodejs shouldn't require `aurelia-pal-nodejs`

### ISSUE THREAD

**Issue by timfish** [aurelia/store#66]
Due to use of `PLATFORM.performance.mark`, `now`, etc, I have to use `aurelia-pal-nodejs` do get `aurelia-store` working in the Electron main process (nodejs). This works but Webpack bundles an additional 6MB of dependencies including jsdom!

My current workaround is:
```
PLATFORM.performance = {
  clearMarks: () => undefined,
  clearMeasures: () => undefined,
  mark: () => undefined,
  now: () => 0
};
```

**Comment by zewa666** [comment]
Uff thats bad. Your workaround is ok since you simply deactivate it. What would be a preferred way to handle this? E.g have the performance part somehow kicked out in prod?

**Comment by timfish** [comment]
I found [this](https://nodejs.org/api/perf_hooks.html#perf_hooks_performance_timing_api) experimental node API but it has some methods missing, otherwise this would just work:
```
import { performance } from 'perf_hooks';

PLATFORM.performance = performance;
```
Webpack is also resolving dependencies in dev mode so my preference is to avoid calling `aurelia-pal-nodejs` `initialize()` entirely. 

If [`ensurePerformance`](https://github.com/aurelia/pal-nodejs/blob/8bc375dad084a3d86b651f57043ef495204b6a01/src/nodejs-pal-builder.ts#L89) from `aurelia-pal-nodejs` was exported it would at least be possible to use only that.

**Comment by zewa666** [comment]
I think the best would be to create a PR over at the pal-nodejs repo to exactly do what you suggested, export ensurePerformance. I wouldn't see a special reason why this shouldn't be possible. In the end sticking to your stubs of PLATFORM is likely not avoidable. At least we should make that as easy as possible.

**Comment by timfish** [comment]
> I think the best would be to create a PR over at the pal-nodejs repo

I will do just this!

**Comment by zewa666** [comment]
Please reference back to this issue for better tracking and later on updating the version number for the dependency

**Comment by timfish** [comment]
I'll take a look at this today

**Comment by zewa666** [comment]
thanks @timfish for your work over at the pal-nodejs repo. As soon as the new version is released I'll update the dep of the store. There are two other features in the pipeline so a release should be available soon after it.

**Comment by zewa666** [comment]
bumped and will be available with the next store release
