### ISSUE TITLE
Log console warning if action runs for a long time

### ISSUE THREAD

**Issue by timfish** [aurelia/store#72]
Well designed actions should not block the dispatch queue for extended periods of time. 

Chrome displays warnings about long running event handlers to highlight potential issues and `aurelia-store` should do the same to ensure developers don't inadvertently block the dispatch queue.

**Comment by zewa666** [comment]
so how should we go about this? As I see it the following should apply:

* a way to enable slow actions warnings
* define the [loglevel of those](https://github.com/aurelia/store/blob/master/src/logging.ts#L18) with default warning?
* define the threshold of what means slow, with default value. 3000ms ?

what do you think about that approach?

**Comment by Vheissu** [comment]
Seems a bit subjective to me what would duration of time could constitute slow, but it's not a bad idea. I am a fan of making API calls from within actions, so I could see wanting quite a high threshold for this because sometimes the internet drops out and things slow down causing delays.

The only thing I would want from this is that the code that checks for long-running actions does not cause a performance bottleneck in my application (unnecessary timers and whatnot doing the checks).

@zewa666 I like the proposed configuration above for something like this.

**Comment by zewa666** [comment]
@Vheissu I agree, the most uncertain thing for me is the default threshold as well. I too do like to encapsulate API calls in Actions, as that is one of the major benefits of being able to isolate businesslogic in reusable parts.

As for the bottlenecks, I don't think so. There are performance checkmarks already all over the place in the internal async queue and if not turned on will not report anything. So I'll merely add another measure call [like here](https://github.com/aurelia/store/blob/master/src/store.ts#L206) somewhere closely after the actual reducer execution if SlowActionOptions.active === true.

Another great question is whether we should enable this feature by default. What are your opinions on that @timfish, @Vheissu ?

**Comment by Vheissu** [comment]
@zewa666 Sounds great to me.

Does Webpack enable performance warnings by default? I can't remember, but I think it does. Those warnings about bundle sizes? Because I think there is value in enabling it by default if it costs nothing in performance calls.

**Comment by timfish** [comment]
I think ideally all hints should be enabled by default, but like Webpack, make it easy to disable all of them:

```
hints: false
```
and 
```
hints: {
  slowActionThreshold: 5000
}
```

**Comment by timfish** [comment]
If you're using the store to control the position of UI elements or you're creating anything interactive, you're going to want to keep all actions under 15-20ms. Even if you're not working with UI elements or don't need performance, any action over 500ms has the potential to make your app seem unresponsive or janky.

While it sounds perfectly possible to make functional, well behaved apps that make blocking calls in actions, should we not be discouraging developers from doing this? With network requests, is there not the potential to block the dispatch queue for the entire HTTP timeout? 

I personally think that the warning should be significantly under 1 second, perhaps as low as 200ms and (separate to this issue) we should supply helpers of added functionality that simplifies dispatching async side-effects. This way, developers will be creating high performance code form the start.

You can still encapsulate API calls or other long running tasks in actions, you just have to dispatch the result into another action.

**Comment by zewa666** [comment]
You're pretty much saying what makes me feel a bit hesitant about this feature. On the one hand it's great for making things visible (which already can be achieved by turning on performance tracking) but on the other with the wrong defaults it may transport the wrong message.

So honestly I'm a bit unsure how to continue with this here

**Comment by timfish** [comment]
No you're right, its a little too opinionated when performance tracking already exists!
