### ISSUE TITLE
Adding the reducer/action params to Redux DevTools

### ISSUE THREAD

**Issue by jmzagorski** [aurelia/store#75]
**I'm submitting a feature request**

**Current behavior:**
Redux DevTools only shows the type when updating per this [line](https://github.com/aurelia/store/blob/master/src/store.ts#L280). Is there an option i need to setup in this library or was this the intended behavior? I did not see anything in the docs about configuring Redux DevTools to show the parameters of the action.

**Expected/desired behavior:**

* **What is the expected behavior?**
All parameter values for the action are shown (aka the payload), maybe under a `params` property or the index number as the property name?

* **What is the motivation / use case for changing the behavior?**
Easier to debug and would be nice to see

**Comment by zewa666** [comment]
I fear I don't really understand what you're looking for. Could you maybe give me a more concrete example or a screenshot to understand what you'd like to have?

**Comment by zewa666** [comment]
Oh ok I think I see now. This is actually a bug. Instead of providing an action, a string of the reducers.name should be there.

But it's nevertheless interesting to hear what you thought about the params. There is no feature like that I'm aware of (aka sending the parameters that were forwarded along the action) to be displayed in the Redux devtools.

**Comment by jmzagorski** [comment]
Yup, sorry about that:

Currently devtools shows the screen shot below: there is only the `type` and I dont see my arguments from my action function.
![image](https://user-images.githubusercontent.com/8404957/47115000-4e118d80-d22b-11e8-934c-f78a5f50a48e.png)

My request is about adding the arguments as in the screen shot below. From this screen shot I added all my arguments under the `params` property as an example, this would be similar to seeing the `payload` in redux
![image](https://user-images.githubusercontent.com/8404957/47115174-bd877d00-d22b-11e8-897b-06180011c6fe.png)

**Comment by zewa666** [comment]
oh wow this is super slick, didn't know or never looked that sub-view. So this indeed is a nice idea. Thanks for the pics ;)

Should we name it `payload` in that case as well or stick with `params`?

The good thing is that this should be pretty straight forward to implement as the internal dispatch has already access to [all params](https://github.com/aurelia/store/blob/master/src/store.ts#L141) and the target function `updateDevToolsState` is private, so no fear about breaking changes when updating the serialization ;)

Now the obvious question you waited for ... would you like to create a PR for that? :)

**Comment by zewa666** [comment]
Params sounds absolutely fine for me

**Comment by dannyBies** [comment]
I think this would be a great addition to aurelia-store!
