### ISSUE TITLE
Upgrading to v 1.2.0 breaks existing app

### ISSUE THREAD

**Issue by stevies** [aurelia/store#78]
Upgraded to aurelia-store v1.2.0 with: `yarn upgrade aurelia-store`.

My previously working app now fails to launch with console error:
```
Error: BindingLanguage must implement inspectTextContent().
```
50 of my previously working unit tests fail with errors same as above.

Had to revert back to 1.1.0 to fix this.

**Comment by zewa666** [comment]
can you upgrade again, then delete the `package-lock.json` and the `node_modules` folder. Then do another `npm install`. As for yarn I'm not sure what their package-lock is, but I guess deleting the node_modules folder should suffice.

The trouble most likely indicates that your app has either resolved the dependencies in a wrong way, or you're still referencing an old version of `aurelia-binding`

**Comment by zewa666** [comment]
related issue: https://github.com/aurelia/store/issues/76

**Comment by stevies** [comment]
That appears to have worked.  I had previously deleted my `node_modules` but not the `yarn.lock` file.

**Comment by stevies** [comment]
Deleting the yarn lock file has forced updates to other packages that I did not want to upgrade at this time (with no way of knowing what has been changed).  Result - broken linting - I am guessing eslint or some related package as been changed.  I will be reverting back to aurelia-store v.1.1.0 - not sure if 1.2.0 gives me anything new that is worth the pain of trying to fix this.

**Comment by stevies** [comment]
Leaving my original yarn.lock unchanged, and manually upgrading a number of other 3rd party modules  (checking nothing breaks in between each), and saving upgrading aurelia-store until the very last, I have managed to get this working.

**Comment by zewa666** [comment]
Yeah so the package-lock, respectively yarn.lock deletion is just the sledgehammer method to see whether this caused the issue. Ideally you would, as you did, go through the single items and see what was causing the trouble. Package managers, naming things and cache invalidation. Some of the hardest things in world :)
