### ISSUE TITLE
Combining multiple reducers in a pipeline

### ISSUE THREAD

**Issue by gins3000** [aurelia/store#89]
**I'm submitting a feature request**

* **Library Version:**
1.3.3

In aurelia-store, a state transition pipeline currently looks like this:
> dispatch -> "before" middlewares -> reducer -> "after" middlewares -> new state

Users have asked (see https://github.com/aurelia/store/issues/85 and https://stackoverflow.com/questions/54266405/aurelia-change-state-twice-in-one-action/54287249) for ways to dispatch "multiple actions at once".
One of the good reasons for wanting to do this, is to avoid the overhead produced by running through each middleware multiple times and by generating multiple new states which trigger UI updates.
Another is to avoid duplicate code by reusing existing reducers.

There were multiple solutions posted, ranging from "Object.assign-ing" two results together to any-casting the store to access the `internalDispatch()` function.

While these all work great and achieve the goal, I think there should be a more intuitive, less boilerplate-y, cleaner way. With this feature request, I'd like to propose one, which in my mind should work. I have not yet tried it, but I'd like to create a PR, if this is something you'd be interested in.

**Current behavior:**
Imagine having two reducers
```ts
function actionA(state: State, param1: string, param2: number): State; 
function actionB(state: State, param3: string, param4: number): State; 
```
and I want to dispatch both of them in a row, avoiding a double state transition.

Currently I'd have to do it by creating a new reducer:
```ts
function actionAandB(state: State, param1: string, param2: number, param3: string, param4: number): State {
  return actionB(actionA(state, param1, param2), param3, param4);
}
```
and then dispatch it like this:
```ts
await store.dispatch(actionAandB, "foo", 43, "bar", 1337);
```
While this is a clean way to do it, it is extra overhead to create these actions, and if you consider that a user might want to combine other transitions like this, the permutations become tedious to implement. If one reducer changes, I have to touch all of the "combo reducers" that use it. Or what if I would like to chain the new `actionAandB` to another one, `actionC` to create `actionAandBandC`? Every new combination makes the parameter list even longer, reducing readability, too.

**Desired behavior:**
What if instead, the same behavior could be achieved out of the box, like this:
```ts
await store
  .pipe(actionA, "foo", 42)
  .pipe(actionB, "bar", 1337)
  .dispatch();
```
`store.pipe(firstReducer, ...params)` would create a "pipe object", which can chain into itself. Each call of `pipe()` continues to build an internal pipeline, which would finally be dispatched by calling `dispatch()`. Illustrated as an interface, it could look similar to this:
```ts
interface DispatchPipe {
  pipe: (reducer: Reducer, ...params) => DispatchPipe;
  dispatch: () => Promise<void>; // nothing happens, until this is called in the end
}
```
Using this new piping method, the transition pipeline would look like this:
> dispatch -> "before" middlewares -> "actionA" reducer -> "actionB" reducer -> "after" middlewares -> new state

or more generally:
> dispatch -> "before" middlewares -> piped reducers -> "after" middlewares -> new state

The existing single `store.dispatch()` action would of course be untouched, making this a new feature, not interfering with existing behaviors.

What do you think? I'm looking forward to feedback and opinions.
As said, if this gets a positive response, I'd like to prepare a pull request with this feature.

Thank you for reading!

**Comment by Vheissu** [comment]
@gins3000 this looks great to me, I really like the idea of piping actions together in this way. My only question is whether or not this could work with the `dispatchify` method which just calls `dispatch` behind the scenes?

You should definitely get a PR and some tests in, it's a great feature to have.

**Comment by gins3000** [comment]
@Vheissu thanks for the positive feedback!

About dispatchify: Great point. That could indeed be a bit tricky. One way I came up with on the spot would be:

Enhance dispatchify to accept an array of reducers:
```ts
function dispatchify<T, P extends any[]>(action: Reducer<T, P> | Reducer<T,any[]>[] | string | string[])
```
so, using dispatchify with the example from above, you would get:
```ts
const dispatchActionAandB = dispatchify([actionA, actionB])

await dispatchActionAandB(param1, param2, param3, param4);
```

or more generally:
`dispatchify([action1, ... actionN])` could produce a function `dispatchA...N(param1_1,...,param1_L1, ..., paramN_1,...,paramN_LN)`

If that would be an acceptable solution, the only problem I'd have to think about more, is how to not lose type safety. I'd love to play around with this a little, but maybe you or someone else has a different idea of how `dispatchify` should behave with piping.

On another note:
I have just loosely played around yesterday trying to see what I'd really have to touch in order to get this functionality in. While trying a few variants, I saw a nice opportunity that would require a breaking change to "internalDispatch", for example.

That leads me to ask, what you would count as a breaking change. I'd usually assume that, as long as I just touch private methods, it'd be non-breaking. But as mentioned above, it was sometimes suggested to any-cast the store to access the privates, in particular `internalDispatch`. Or if someone uses plain JS, "private" means nothing in that context anyway. 

If it is desired that `internalDispatch` (and other privates) retain current functionality, I could of course work around that limitation, but it would be good to know if I'm allowed to "break" privates if that would lead to a prettier end result.

**Comment by zewa666** [comment]
Hey @gins3000, thanks for feature request. Great idea.

With regards to dispatchify, the curried approach you've shown in your edit feels like the right way to go for me, though I'd like to have @Vheissu's input on this one as well.

About breaking changes. Private API is meant to be private for exactly the reason to not introduce breaking changes, when the functions get touched. As long as the public API surface after your change does what it did before you're good. People doing `any` casts to access private functions are typically well aware that they're violating the visibility contract and thus could end up with a borked situation.

**Comment by zewa666** [comment]
As a help for implementing the curried approach in a type-safe way this article might help https://medium.freecodecamp.org/typescript-curry-ramda-types-f747e99744ab

**Comment by zewa666** [comment]
Additionally here's a list of things we should keep in mind for the implementation

- [ ] Logging
- [ ] Performance tracking 
- [ ] On-the-fly registration of resulting reducer
- [ ] Naming convention (important for Redux DevTools)
- [ ] Params merging for middleware CallingAction
- [ ] History support

**Comment by ConductedClever** [comment]
@zewa666, Thanks for mentioning me. And also I admire and respect @gins3000 for these great recommendations.
Also I will mention @mmdrn as he is the person asked the linked question on stackoverflow.

And back to the solutions, I really liked the piping approach on dispatching actions. The second solution about chained function calls on dispatchify is also good, but I personally prefer to have it also as piped. I mean I prefer to use dispatchify these ways:
the current behavior:
```javascript
const dispatchActionA = dispatchify(actionA);
await dispatchActionA(param1, param2);
```
and the piped way:
```javascript
const dispatchActionAandB = dispatchify(actionA, actionB);
await dispatchActionAandB
    .pipe(actionA, param1, param2)
    .pipe(actionB, param3, param4)
    .dispatch();
```
to be more uniform to the newly proposed behavior of `store.dispatch` itself.

And about addressing my needs, I was solving my issues this way:
1. **changing state twice in one action**: I was calling the second action in the first action and using its result as the current state passing to Object assign, which I will change to this new way in future (after release).
2. **dispatching action inside action**: was canceled and replaced with the above solution.
3. **disposing actions in async way**: also was solved by substituting our layers of action and service to make jobs async before reaching actions.

So this issue will make our code more neat and tidy for the 1st and 2nd one.
Thanks.

**Comment by ConductedClever** [comment]
And also I think it will be good to do this on registering and unregistering mechanisms. For example instead of doing this:
```javascript
this.store.registerAction('DemoActionA', demoActionA); 
this.store.registerAction('DemoActionB', demoActionB);
```
do this one:
```javascript
this.store.registerAction
    .pipe('DemoActionA', demoActionA)
    .pipe('DemoActionB', demoActionB);
```
or
```javascript
this.store
    .pipe(registerAction, 'DemoActionA', demoActionA)
    .pipe(registerAction, 'DemoActionB', demoActionB);
```
Just as an Idea (not a need indeed).

**Comment by gins3000** [comment]
Thanks for the merge @zewa666 !
I guess it makes sense to keep this issue open, until the piped version of `dispatchify` is ready too? I'll see if I can get to it some time this month.

**Comment by zewa666** [comment]
On contraire, thank you for the hard work @gins3000. Yes, I guess keeping the issue around for a bit longer might make sense, especially in the light of dispatchify support and potential history helpers that might arise. May I also draw your attention to the [PR for the plugins docs](https://github.com/aurelia/documentation/pull/416)?

**Comment by gins3000** [comment]
@zewa666, thanks! I have left a comment in aurelia/documentation/pull/416 with suggestions.
