### ISSUE TITLE
Commit button in redux dev tools does not work

### ISSUE THREAD

**Issue by jmzagorski** [aurelia/store#91]
**I'm submitting a bug report**

* **Library Version:**
1.3.4

* **JSPM OR Webpack AND Version**
Webpack 4 .15.1

* **Browser:**
chrome, firefox, probably others

* **Language:**
TypeScript

**Current behavior:**
The commit button throws an error because `message.state` is undefined [here](https://github.com/aurelia/store/blob/master/src/store.ts#L277)

**Expected/desired behavior:**

* **What is the expected behavior?**
Commit button is suppose to 'save' a state and wipe out the history of actions. First gif is from a redux app. Second gif is from an aurelia-store app

![2019-04-26_11-23-29](https://user-images.githubusercontent.com/8404957/56818647-10af3d80-6816-11e9-95f7-9112a51995dc.gif)
![2019-04-26_11-24-32](https://user-images.githubusercontent.com/8404957/56818652-13aa2e00-6816-11e9-8e44-529fcffe6460.gif)

* **What is the motivation / use case for changing the behavior?**
Fixing a broken feature. I tried to find the source of where this is happening, but it was hard to debug it in the browser with the minified devtools source code. Or is there an option I need to set for this to work? If that is the case I could not find the documentation and I would think this should work by default.

**Comment by dannyBies** [comment]
As far as I know there is no way to [commit/reset/revert/sweep actions](https://github.com/gaearon/redux-devtools-log-monitor/blob/master/README.md#features.) using aurelia store. So this features would have to be implemented.

**Comment by zewa666** [comment]
Hi all,

the issue happens [here](https://github.com/aurelia/store/blob/master/src/store.ts#L277) when parsing the state from the devtools message.

The message itself looks something like this:

```json
{
  "id": "1",
  "payload": {
    "timestamp": 1556522363871,
    "type": "COMMIT"
  },
  "source": "@devtools-extension",
  "state": undefined,
  "type": "DISPATCH"
}
```

so in order to properly check for those actions, besides checking the response type, we'd also need to check the payloads type and do something specific for `COMMIT`.

And here's the thing where I'm not sure what to do. You say it should "save the state and wipe out the history". That sounds like truncate the whole store (re-initialize) and make current state the new INITIAL_STATE right?

**Comment by jmzagorski** [comment]
I have not had a lot of time to look into the inner workings of the dev tools, but that seems right. From their docs:

> "Commit” removes all actions in your log, and makes the current state your initial state. This is useful when you start working on a feature and want to remove the previous noise

We should probably make sure all those buttons work once the commit starts working.

**Comment by zewa666** [comment]
Hi @jmzagorski and @dannyBies. I'm sorry this took so long but I've finally managed to take a look at those button actions and have created a PR over [here](https://github.com/aurelia/store/pull/104). If you guys could perhaps give it a look and at best even check it out, that would be of tremendous help

**Comment by zewa666** [comment]
merged the PR. It does not include all the features from DevTools but I guess we're on to a good start. I'll close this issue but we can resurrect it if more is needed

**Comment by jmzagorski** [comment]
Sorry I missed this, been away from client side development for a bit. Thanks for doing this.
